### ISSUE TITLE
There is no simple way to deal with missing values in response surface

### ISSUE THREAD

**Issue by imshakib** [arnaldpuy/sensobol#7]
Sobol_indices gives error if there is a missing value (NA or NaN) in the model response. There doesn't seem to be a way to avoid this. The error is: 
"
Error in if (const(t, min(1e-08, mean(t, na.rm = TRUE)/1e+06))) { : 
  missing value where TRUE/FALSE needed
"

**Comment by arnaldpuy** [comment]
Thank you for this observation. Indeed, sobol_indices requires a numeric vector without NA or NaN values. I will explicitly inform about this in the next sensobol upgrade.

**Comment by RobinM92** [comment]
Hi @arnaldpuy,
Is there already a solution for this issue? At the moment I am circumventing this by filtering the model response for NaN/NAs and reducing the parameter matrix accordingly, but this can still cause issues as, because of the repetitions, N and Y are then no longer integer multiples of each other. So a better solution (e.g. the option to skip NAs in the SI calculation) would be amazing. 
So in short, is there already a workflow to apply this on complex models which might not converge for each set of parameters?
